image: alpine:latest

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - unit-test
  - package-deps
  - package-build
  - package-test
  - publish
  - publish-artifacts

include:
  - template: Code-Quality.gitlab-ci.yml
  - local: '/.gitlab-ci/Jobs/php_unit_tests.yml'
  - local: '/.gitlab-ci/Jobs/artifact_build.yml'
  - local: '/.gitlab-ci/Jobs/debian_package_build.yml'
  - local: '/.gitlab-ci/Jobs/packages_tests.yml'
  - local: '/.gitlab-ci/Jobs/style_check.yml'
  - local: '/.gitlab-ci/Jobs/rpm_package_build.yml'

code_quality:
  stage: unit-test
