.cs-check:
  stage: unit-test
  variables:
    PHP_VERSION: "7.3"
  image: $CI_REGISTRY_IMAGE_TEST:$PHP_VERSION
  allow_failure: true
  script:
    - composer config --global process-timeout 2000
    - composer install --dev --no-interaction
    - composer cs-check
    - composer stan
    - composer psalm

check-style-strict:
  extends: .cs-check
  allow_failure: false
  only:
    - common

check-style:
  extends: .cs-check
  except:
    - common
